import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";
import Provider from "@/components/LiveblocksProvider";
import { ThemeProviderWrapper } from "@/components/ThemeProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Diagramly",
  description: "Generated by Diagramly",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
  <head>
    <Script
      async
      src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID}`}
      strategy="lazyOnload"
      crossOrigin="anonymous"
    />
  </head>

  <body className={inter.className}>
    <ThemeProviderWrapper attribute="class" defaultTheme="light" enableSystem={false}>
      <Provider>
        {children}
        <Toaster />
      </Provider>
    </ThemeProviderWrapper>
  </body>
</html>
  );
}
